
name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test-maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Launch tests
      run: mvn test
      env:
        CLOUD_TEST: 'TRUE'
    
  build:
    runs-on: ubuntu-latest
    needs: test-maven
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github 
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn package -DskipTests 
      env:
        CLOUD_TEST: 'TRUE'
